version: "3"
services:
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.6.0
    environment:
      # set a unique cluster name to avoid joining another cluster
      # - cluster.name=my-play-cluster

      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
      - bootstrap.memory_lock=true
      - discovery.type=single-node
      - xpack.security.enabled=false
      - xpack.monitoring.enabled=false # cuts down on server log noise
      # - logger.level=DEBUG # very noisy

      # These are required for elasticsearch-head
      # - http.cors.enabled=true
      # - http.cors.allow-origin="*" # note this is unsafe for any real use
    ulimits:
      memlock:
        soft: -1
        hard: -1
    # mem_limit: 1G
    # resources:
    #   limits:
    #     memory: 1G
    volumes:
      - ./elasticsearch-7.6.yml:/usr/share/elasticsearch/config/elasticsearch.yml
      # - ./elasticsearch_data:/usr/share/elasticsearch/data
    ports:
      # host:container
      # 9200 for REST
      - "8200:9200"
      # 9300 for inter-node communication
      - "8300:9300"
  kibana:
    image: docker.elastic.co/kibana/kibana:7.6.0
    ports:
      # host:container
      - 4601:5601
    depends_on:
      - elasticsearch
  head:
    image: mobz/elasticsearch-head:5
    ports:
      # host:container
      - 8100:9100
