# -*- mode: ruby -*-
# vi: set ft=ruby :

VAGRANTFILE_API_VERSION = "2"

Vagrant.configure(VAGRANTFILE_API_VERSION) do |config|
  config.vm.box = "ubuntu/trusty64"

  # Create a forwarded port mapping which allows access to a specific port
  # within the machine from a port on the host machine. In the example below,
  # accessing "localhost:8085" will access port 80 on the guest machine.
  #
  # We use 8085 because it is not popular with the other local servery things
  # we run.
  config.vm.network "forwarded_port", guest: 80, host: 8085

  config.vm.provider "virtualbox" do |vb|
    # Increase memory to a more sensible default for running asset
    # precompilation and other memory-intensive tasks
    vb.customize ["modifyvm", :id, "--memory", "1024"]
  end

  # Speed up provisioning by turning on caching of:
  #
  #   * downloaded apt packages
  #   * ruby gems used by chef
  #   * chef DK deb
  #
  # Default cache location: ~/.vagrant.d/cache (on host)
  #
  if Vagrant.has_plugin?("vagrant-cachier")
    config.cache.scope = :box
  end

  config.berkshelf.enabled = false
  config.vm.provision "shell", path: "provision-vagrant.sh"
end
