# -*- mode: ruby -*-
# vi: set ft=ruby :

VAGRANTFILE_API_VERSION = "2"

Vagrant.configure(VAGRANTFILE_API_VERSION) do |config|
  config.vm.box = "ubuntu/xenial64"
  # config.vm.network "forwarded_port", guest: 3000, host: 3001

  config.vm.provider "virtualbox" do |vb|
    vb.name = "Assembly Language Play"
    # Increase memory to a more sensible default for running asset
    # precompilation and other memory-intensive tasks
    # vb.customize ["modifyvm", :id, "--memory", "1024"]
  end

  # Speed up provisioning by turning on caching of:
  #
  #   * downloaded apt packages
  #   * ruby gems used by chef
  #   * chef DK deb
  #
  # Default cache location: ~/.vagrant.d/cache (on host)
  #
  if Vagrant.has_plugin?("vagrant-cachier")
    config.cache.scope = :box
  end

  config.berkshelf.enabled = false
  config.vm.provision "shell", path: "provision.sh"
end
