#include<stdio.h>

// it does not matter how big this array gets it will not change the size of
// the binary generated by gcc because this array is allocated in the .bss
// section
static char lots[999999999999999999];

int main(int argc, char *argv[])
{
  return 0;
}
