

default: build_1 build_2 build_3

build_1:
	cobc -x -Wall -debug -o ./bin/TerminalTest ./TerminalTest.cbl

build_2:
	cobc -x -Wall -debug -o ./bin/HelloWorldFree ./HelloWorldFree.cbl

build_3:
	cobc -x -Wall -debug -o ./bin/HelloWorld ./HelloWorld.cbl

cobol_tutorial:
	cobc -x -Wall -debug -o ./bin/cobol_tutorial ./cobol_tutorial.cbl