

default: build_1 build_2 build_3

build_1:
	cobc -x -debug -o ./bin/TerminalTest ./TerminalTest.cbl

build_2:
	cobc -x -debug -free -o ./bin/HelloWorldFree ./HelloWorldFree.cbl

build_3:
	cobc -x -debug -o ./bin/HelloWorld ./HelloWorld.cbl
