#!/usr/bin/env ruby

PROJECT_ROOT = File.absolute_path(File.join(__dir__, "..")).to_s

puts "Changing working directory to project root at '#{PROJECT_ROOT}'"

Dir.chdir(PROJECT_ROOT) do
  puts "Tailing nginx access.log"
  `tail -f log/access.log`
end
