---
driver:
  name: vagrant

provisioner:
  name: chef_zero
  # You may wish to disable always updating cookbooks in CI or other testing environments.
  # For example:
  #   always_update_cookbooks: <%= !ENV['CI'] %>
  always_update_cookbooks: true

verifier:
  name: inspec

platforms:
  - name: xenial64
    driver:
      box: ubuntu/xenial64
      box_url: ubuntu/xenial64


suites:
  - name: default
    run_list:
      - recipe[motd_attrs::default]
    verifier:
      inspec_tests:
        - test/smoke/default
    attributes:
